name: Deploy Project
on: pull_request

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the Code from Repository
        uses: actions/checkout@v4
      - name: List Files
        run: ls -la        
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: 18
      - name: Navigate to Project Directory and Install NPM
        run: cd npm_project && npm install
      - name: List Files
        run: ls -la

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check working directory
        run: pwd
      - name: List Files
        run: ls -la
      - name: Run Tests
        run: cd npm_project && npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [setup, test]
    steps:
      - name: Build
        run: cd npm_project && npm run build
      - name: Deploy
        run: echo Deployment Successful
