name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print workspace
        run: echo "The workspace is located at ${{ github.workspace }}"
        
      - name: List files in workspace
        run: ls -la ${{ github.workspace }}

