name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the Code from Repositary
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: 18
      - name: List Files
        run: ls -la
      - name: Navigate to Project Directory and Install NPM
        run: cd npm_project && npm install
        shell: bash
      - name: Working Directory
        run : pwd     
      - name: Run Tests
        run: npm test 
    