name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the Code from Repositary
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test 
    